serviceConfig:
  scheme: http://
  hostName: andromeda-71.ics.uci.edu
  port: 7623
  path: /api/idm

loggerConfig:
  outputDir: ./logs/
  outputFile: idm.log

databaseConfig:
  dbUsername: cs122b_db43
  dbPassword: BUXc2KZ57XOJ
  dbHostname: matt-smith-v4.ics.uci.edu
  dbPort: 3306
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: cs122b_db43
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST

sessionConfig:
  timeout: 3600000
  expiration: 10800000
